# =============================================================================
# roles/lighthouse-role/handlers/main.yml — Обработчики для Lighthouse
# =============================================================================
---
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded